# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.service_client import ServiceClient
from msrest import Configuration, Serializer, Deserializer
from .version import VERSION
from msrest.exceptions import HttpOperationError
from .operations.get_operations import GetOperations


class APIConfiguration(Configuration):
    """Configuration for API
    Note that all parameters used to create this instance are saved as instance
    attributes.

    :param str base_url: Service URL
    """

    def __init__(
            self, base_url=None):

        if not base_url:
            base_url = 'http://localhost'

        super(APIConfiguration, self).__init__(base_url)

        self.add_user_agent('api/{}'.format(VERSION))


class API(object):
    """API

    :ivar config: Configuration for client.
    :vartype config: APIConfiguration

    :ivar get: Get operations
    :vartype get: hello.operations.GetOperations

    :param str base_url: Service URL
    """

    def __init__(
            self, base_url=None):

        self.config = APIConfiguration(base_url)
        self._client = ServiceClient(None, self.config)

        client_models = {}
        self.api_version = '1.0'
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

        self.get = GetOperations(
            self._client, self.config, self._serialize, self._deserialize)
